import Head from 'next/head'
import s from '../wishlist/wishlist.module.scss'
// components
import Card from '@/components/card'
import Breadcrumbs from '@/components/breadcrumbs'
// link
import Link from 'next/link'
// imgs
import Image from 'next/image'
import Delete from "@/assets/img/Group 9.svg"
import Arrow from "@/assets/img/arrowleft.svg"
import Card_Photo from "@/assets/img/image 3.png"

const wishlist = () => {
  return (
    <>
    <Head>
        <title>Wish List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.wishlist}>
          <Breadcrumbs></Breadcrumbs>
          <h1 className={s.wishlist__title}>Wishlist</h1>
          <h2 className={s.wishlist__count}>158 products</h2> {/* use lenght of products list to display count of products */}
          <div className={s.wishlist__filter}>
            <button className={`${s.wishlist__filter_category} ${s.active}`}>
              <h2 className={s.wishlist__filter_category_text}>All products</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_category}`}>
              <h2 className={s.wishlist__filter_category_text}>Phones</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_category}`}>
              <h2 className={s.wishlist__filter_category_text}>Accessories</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_new}`}>
              <h2 className={s.wishlist__filter_new_text}>New category</h2>
            </button>
          </div>
          <div className={s.wishlist__info}>
            <h2 className={s.wishlist__info_text}>Photo</h2>
            <h2 className={s.wishlist__info_text}>Product code</h2>
            <h2 className={s.wishlist__info_text}>Name</h2>
            <h2 className={s.wishlist__info_text}>Stock</h2>
            <h2 className={s.wishlist__info_text}>QTY</h2>
            <h2 className={s.wishlist__info_text}>Price</h2>
            <h2 className={s.wishlist__info_text}></h2>
            <h2 className={s.wishlist__info_text}>Switch</h2>
            <h2 className={s.wishlist__info_text}>Image</h2>
          </div>
          <div className={s.wishlist__list}>
            {/* using product list from server to display items */}
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} description={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
          </div>
          <div className={s.wishlist__extra}>
            <div className={s.wishlist__extra_back}>
              <Image className={s.wishlist__extra_back_link_arrow} src={Arrow} alt='arrow'></Image>
              <Link className={s.wishlist__extra_back_link} href={"/"}>Back</Link>
            </div>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2 className={s.wishlist__extra_btn_text}>Add product</h2>
            </button>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2 className={s.wishlist__extra_btn_text}>Add to cart</h2>
            </button>
          </div>
        </section>
      </main>
    </>
  )
}

export default wishlist