import Head from 'next/head'
import s from '../wishlist/wishlist.module.scss'
// components
import Card from '@/components/card'
import Breadcrumbs from '@/components/breadcrumbs'
// link
import Link from 'next/link'
// imgs
import Image from 'next/image'
import Delete from "@/assets/img/Group 9 black.svg"
import Arrow from "@/assets/img/arrowleft.svg"
import Card_Photo from "@/assets/img/image 3.png"

const wishlist = () => {
  return (
    <>
    <Head>
        <title>Wish List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.wishlist}>
          <Breadcrumbs></Breadcrumbs>
          <h1 className={s.wishlist__title}>Wishlist</h1>
          <h2 className={s.wishlist__count}>158 products</h2> {/* use lenght of products list to display count of products */}
          <div className={s.wishlist__filter}>
            <div className={`${s.wishlist__filter} ${s.container}`}>
              <button className={s.wishlist__filter_category}>
                <h2>All products</h2>
                <Image src={Delete} alt='delete-btn'></Image>
              </button>
              <button className={s.wishlist__filter_category}>
                <h2>Phones</h2>
                <Image src={Delete} alt='delete-btn'></Image>
              </button>
              <button className={s.wishlist__filter_category}>
                <h2>Accessories</h2>
                <Image src={Delete} alt='delete-btn'></Image>
              </button>
            </div>
            <button className={`${s.wishlist__filter_new}`}>
              <h2>New</h2>
            </button>
          </div>
          <div className={s.wishlist__info}>
            <h2>Photo</h2>
            <h2>Product code</h2>
            <h2>Name</h2>
            <h2></h2>
            <h2>Stock</h2>
            <h2>QTY</h2>
            <h2>Price</h2>
            <h2></h2>
            <div className={s.wishlist__info_switch}>
              <h2>Switch</h2>
              <h2>Image</h2>
            </div>
          </div>
          <div className={s.wishlist__list}>
            {/* using product list from server to display items */}
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='NY' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Washington' quantity={56} price={48}></Card>
            <Card img={Card_Photo} code={5894684854} name={"Power bank (UMB) XO PR156, 30000 mAh, 3USB + Type-C + Lighting, Quick Charge, Power Delivery, 22.5W, Black"} stock='Kyiv' quantity={56} price={48}></Card>
          </div>
          <div className={s.wishlist__extra}>
            <div className={s.wishlist__extra_back}>
              <Image className={s.wishlist__extra_back_link_arrow} src={Arrow} alt='arrow'></Image>
              <Link href={"/"}>Back</Link>
            </div>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2>Add product</h2>
            </button>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2>Add to cart</h2>
            </button>
          </div>
        </section>
      </main>
    </>
  )
}

export default wishlist