import Head from 'next/head'
import s from '@/styles/Home.module.scss'
// link
import Link from 'next/link'
// imgs
import Image from 'next/image'
import Delete from "@/assets/img/Group 9.svg"
import Arrow from "@/assets/img/arrowleft.svg"

export default function Home() {
  return (
    <>
      <Head>
        <title>Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={s.wishlist}>
          <h1 className={s.wishlist__title}>Wishlist</h1>
          <h2 className={s.wishlist__count}>158 products</h2> {/* use lenght of products list to display count of products */}
          <div className={s.wishlist__filter}>
            <button className={`${s.wishlist__filter_category} ${s.active}`}>
              <h2 className={s.wishlist__filter_category_text}>All products</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_category}`}>
              <h2 className={s.wishlist__filter_category_text}>Phones</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_category}`}>
              <h2 className={s.wishlist__filter_category_text}>Accessories</h2>
              <Image className={s.wishlist__filter_category_img} src={Delete} alt='delete-btn'></Image>
            </button>
            <button className={`${s.wishlist__filter_new}`}>
              <h2 className={s.wishlist__filter_new_text}>New category</h2>
            </button>
          </div>
          <div className={s.wishlist__info}>
            <h2 className={s.wishlist__info_text}>Photo</h2>
            <h2 className={s.wishlist__info_text}>Product code</h2>
            <h2 className={s.wishlist__info_text}>Name</h2>
            <h2 className={s.wishlist__info_text}></h2>
            <h2 className={s.wishlist__info_text}>Stock</h2>
            <h2 className={s.wishlist__info_text}>QTY</h2>
            <h2 className={s.wishlist__info_text}>Price</h2>
            <h2 className={s.wishlist__info_text}></h2>
            <h2 className={s.wishlist__info_text}>Switch</h2>
            <h2 className={s.wishlist__info_text}>Photo</h2>
          </div>
          <div className={s.wishlist__list}>

          </div>
          <div className={s.wishlist__extra}>
            <div className={s.wishlist__extra_back}>
              <Image className={s.wishlist__extra_back_link_arrow} src={Arrow} alt='arrow'></Image>
              <Link className={s.wishlist__extra_back_link} href={"/"}>Back</Link>
            </div>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2 className={s.wishlist__extra_btn_text}>Add product</h2>
            </button>
            <button className={`${s.wishlist__extra_btn}`}>
              <h2 className={s.wishlist__extra_btn_text}>Add to cart</h2>
            </button>
          </div>
        </section>
      </main>
    </>
  )
}